plugins = []
headers = []

[functions]

[functions."*"]

[build]
publish = "G:\\zichan\\xinzichan\\client\\dist"
publishOrigin = "ui"
commandOrigin = "ui"
base = "G:\\zichan\\xinzichan\\client"
command = "npm run build"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[redirects]]
from = "/*"
to = "/index.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]